add_newline = false

[directory]
truncate_to_repo = false

[git_branch]
symbol = "Branch "

[golang]
symbol = 'Go '

[nodejs]
symbol = 'Node '

[ruby]
symbol = 'Ruby '

[python]
symbol = 'Python '

[php]
symbol = 'PHP '

[terraform]
symbol = 'Terraform '

[package]
symbol = 'Package '
disabled = true

[aws]
symbol = 'AWS '

[vagrant]
symbol = 'Vagrant '
