add_newline = false

[directory]
truncate_to_repo = false

[git_branch]
symbol = "Branch "

[golang]
symbol = 'Go '

[nodejs]
symbol = 'Nodejs '

[ruby]
symbol = 'Ruby '

[python]
symbol = 'Python '

[php]
symbol = 'PHP '

[dart]
symbol = 'Dart '

[terraform]
symbol = 'Terraform '

[package]
symbol = 'Package '
disabled = true

[aws]
symbol = 'AWS '

[gcloud]
symbol = 'GCP '
format = 'on [$symbol$project (\($region\) )]($style) '

[battery]
disabled=true
